### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by liumin13** [mtnygard/javafx-wrapper#1]
when I first use this "(use 'javafx.scene.layout)" it throw "ClassNotFoundException javafx.scene.layout.CornerRadiiConverter" and I use "(require '[javafx.scene.layout :as l])" it throw "NoClassDefFoundError Could not initialize class javafx.scene.layout__init" . Now how can I make this working.

**Comment by mtnygard** [comment]
I have reproduced this error.

It's very odd, though. The JDK docs show that CornerRadiiConverter should exist. However, I don't find it in my latest JDK.

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Can you post the JDK version you are using?

**Comment by mtnygard** [comment]
Aha. I found http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8096129 in which that class is removed from the public API. Very odd that the [Javadoc](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/package-summary.html) still includes it.

**Comment by mtnygard** [comment]
Fixed. Thanks!
